kind: Deployment
apiVersion: apps/v1
metadata:
   name: portfolio
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: portfolio
   template:
      metadata:
        labels:
          app: portfolio
      spec:
       containers:
        - name: portfolio
          image: rangarohit/pip
          imagePullPolicy: Always
          ports:
          - containerPort: 80
