kind: Service                             
apiVersion: v1
metadata:
  name: portfolio
  labels:
    app: portfolio
spec:
  ports:
    - port: 8080                               
      # targetPort: 80                    
      # nodePort: 31200
  selector:
    app: portfolio                    
  type: LoadBalancer      